# Generated by Django 2.2.9 on 2020-01-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='tasks_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество задач в работе'),
        ),
    ]
