# Generated by Django 2.2.9 on 2020-01-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
