# Generated by Django 2.2.9 on 2020-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0003_auto_20200120_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmachine',
            name='factory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ЭЦП'),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='validity',
            field=models.IntegerField(default=12, verbose_name='Срок действия(месяцев)'),
        ),
    ]
