# Generated by Django 2.2.9 on 2020-01-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_system', '0005_auto_20200124_1136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
    ]
